### ISSUE TITLE
Some bugs in visualization

### ISSUE THREAD

**Issue by TheFatBlue** [secureai4code/adversarial-codegen#15]
I found there are some bugs in viz code.
- `visualizer` will generate two same pictures
- when the model name is too long, it will exceed the box
- the legend doesn't provide enough information.
I'll fix them asap

**Comment by TomasAndersonFang** [comment]
此issue已迁移到新仓库: https://github.com/safeai4code/RobustEval-CLM/issues/29

**Comment by TomasAndersonFang** [comment]
This issue has been migrated to the new repository: https://github.com/safeai4code/RobustEval-CLM/issues/29
