### ISSUE TITLE
Implementation for Sentence-level adversarial attack

### ISSUE THREAD

**Issue by TomasAndersonFang** [secureai4code/adversarial-codegen#3]
Intro:

We'll build a new sentence-level adversarial attack method: for a natural language (English) prompt for a coding task, we first translate it into another natural language, such as Chinese, and then translate it back. We regard this back-translated sentence as the adversarial sample to the original one.

**Comment by TomasAndersonFang** [comment]
The key problem: which tool we should select for translation?

**Comment by maxxbw54** [comment]
We could start with the same tool as the reference. @TomasAndersonFang  Can we?

**Comment by TomasAndersonFang** [comment]
> We could start with the same tool as the reference. @TomasAndersonFang Can we?

I'll try to follow the [repo](https://github.com/GEM-benchmark/NL-Augmenter) mentioned in the original paper.

**Comment by TomasAndersonFang** [comment]
> We could start with the same tool as the reference. @TomasAndersonFang Can we?

I checked this repo, and it's a little old. So finally, I directly used transformers translation pipeline to build our translator, and used "facebook bart" as the default model.

**Comment by TomasAndersonFang** [comment]
This issue has been migrated to the new repository: https://github.com/safeai4code/RobustEval-CLM/issues/41
